services:
  db:
    image: postgres:16-alpine
    container_name: nexus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nexus_db
      - POSTGRES_USER=nexus_user
      - POSTGRES_PASSWORD=nexus_pass
      - TZ=America/Lima
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_user -d nexus_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexus_redis
    environment:
      - TZ=America/Lima
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: nexus_web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - TZ=America/Lima
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health/live/', timeout=3)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    stop_grace_period: 15s

  worker:
    build: .
    container_name: nexus_worker
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    env_file: .env
    environment:
      - TZ=America/Lima
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stop_grace_period: 30s

  beat:
    build: .
    container_name: nexus_beat
    command: ["celery", "-A", "config", "beat", "--loglevel=info", "-s", "/app/celerybeat-schedule/celerybeat-schedule"]
    volumes:
      - .:/app
      - beat_data:/app/celerybeat-schedule
    env_file: .env
    environment:
      - TZ=America/Lima
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stop_grace_period: 30s

  flower:
    build: .
    container_name: nexus_flower
    command: ["celery", "-A", "config", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=America/Lima
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - CELERY_BROKER_URL=redis://nexus_redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  beat_data: # Vital para que Beat no pierda el hilo de las tareas programadas
