# Generated by Django 6.0.3 on 2026-04-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_order_delivery_org_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nota',
            field=models.TextField(blank=True, default='', help_text='Nota de cambios en la orden (por qué se incrementó, decrementó o borró productos)'),
        ),
    ]
