# Generated by Django 6.0.3 on 2026-04-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_order_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workflow_processed',
            field=models.BooleanField(default=False, help_text='Flag que indica si el flujo post-pago ya fue ejecutado'),
        ),
    ]
