# Generated by Django 6.0.2 on 2026-02-23 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_order_subtotal_order_tax_amount_taxconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order_count', models.IntegerField()),
                ('data', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
