# Generated by Django 6.0.3 on 2026-04-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_order_workflow_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', help_text='Estado del workflow post-pago: pending | processing | completed | failed', max_length=20),
        ),
    ]
