# Generated by Django 6.0.3 on 2026-04-30 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_order_workflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Inicio'), ('action_executed', 'Acción ejecutada'), ('invoicing_triggered', 'Facturación disparada'), ('error', 'Error'), ('completed', 'Completado'), ('skipped_already_processed', 'Saltado: ya procesado'), ('skipped_invalid_status', 'Saltado: estado inválido')], help_text='Acción del workflow', max_length=30)),
                ('status', models.CharField(default='pending', help_text='Estado en momento del evento', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Cuándo ocurrió')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos contextuales (error, retry_count, etc)')),
                ('order', models.ForeignKey(help_text='Orden asociada', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='domain.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'verbose_name': 'Workflow Log',
                'verbose_name_plural': 'Workflow Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
