# Generated by Django 6.0.3 on 2026-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Producto Dañado'), ('MISTAKE', 'Error en Envío'), ('DISSATISFIED', 'Cliente Insatisfecho'), ('EXPIRED', 'Producto Vencido'), ('OTHERS', 'Otros')], default='DISSATISFIED', max_length=20),
        ),
    ]
