# Generated by Django 6.0.3 on 2026-03-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_alter_orderreturn_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_email',
            field=models.EmailField(default='subliangel@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
