# Generated by Django 6.0.3 on 2026-05-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_companyinvoiceconfig_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_hash',
            field=models.CharField(blank=True, help_text='Hash CDR recibido de Nubefact — confirma que Nubefact acepto el comprobante', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_external_id',
            field=models.CharField(blank=True, help_text='ID externo de factura: serie-numero (ej. B001-42)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola de emision'), ('processing', 'Procesando emision'), ('submitted', 'Enviado a Nubefact'), ('sync_pending', 'Esperando confirmacion SUNAT'), ('sync_processing', 'Consultando SUNAT'), ('accepted', 'Aceptado por SUNAT'), ('observed', 'Observado por SUNAT'), ('rejected', 'Rechazado por SUNAT'), ('retrying', 'Reintentando'), ('failed', 'Fallo permanente'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado del ciclo de facturacion: emision → Nubefact → SUNAT reconciliacion', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Numero de consultas realizadas a Nubefact')),
                ('next_retry_at', models.DateTimeField(help_text='Proxima ventana de consulta — backoff exponencial')),
                ('last_response', models.JSONField(blank=True, help_text='Ultima respuesta JSON de Nubefact (para debug y auditoria)', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Ultimo mensaje de error recibido', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp del lock activo — null si no esta siendo procesada', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp en que alcanzo estado terminal (accepted/rejected/cancelled)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='Orden cuya factura esta pendiente de sincronizacion con SUNAT', on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_entry', to='domain.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'verbose_name': 'Cola de Sincronizacion de Factura',
                'verbose_name_plural': 'Cola de Sincronizacion de Facturas',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='domain_invo_status_23bc58_idx'), models.Index(fields=['organization', 'status'], name='domain_invo_organiz_c5500d_idx')],
            },
        ),
    ]
