# Generated by Django 6.0.3 on 2026-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_purchaseorder_purchaseorderitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='reentered_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Producto Dañado (No reingresa)'), ('MISTAKE', 'Error en Envío'), ('DISSATISFIED', 'Cliente Insatisfecho'), ('EXPIRED', 'Producto Vencido'), ('OTHERS', 'Otros')], default='DISSATISFIED', max_length=20),
        ),
    ]
