# Generated by Django 6.0.3 on 2026-05-24 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_invoicesyncqueue_observability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sale', 'Venta'), ('return', 'Devolución'), ('adjustment', 'Ajuste Manual')], default='sale', max_length=20)),
                ('invoice_external_id', models.CharField(help_text='Snapshot del ID externo Nubefact al momento de generar el asiento', max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, help_text='Total bruto de la factura (incluye impuestos)', max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, help_text='Monto de impuestos (IGV)', max_digits=14)),
                ('amount_net', models.DecimalField(decimal_places=2, help_text='Base imponible (sin impuestos)', max_digits=14)),
                ('currency', models.CharField(default='PEN', help_text='Código ISO 4217 de la moneda', max_length=3)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha contable del asiento — normalmente la fecha de aceptación SUNAT')),
                ('notes', models.TextField(blank=True, help_text='Notas internas del asiento (ajustes manuales, referencias, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='Orden origen — OneToOne garantiza un solo asiento por factura aceptada', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_entry', to='domain.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
            },
        ),
        migrations.CreateModel(
            name='AccountingEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(help_text='Código de cuenta contable (placeholder — referenciará ChartOfAccounts en futuro)', max_length=20)),
                ('description', models.CharField(help_text='Descripción de la partida', max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Monto débito de la partida', max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Monto crédito de la partida', max_digits=14)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='domain.accountingentry')),
            ],
            options={
                'verbose_name': 'Línea de Asiento Contable',
                'verbose_name_plural': 'Líneas de Asiento Contable',
            },
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['organization', 'entry_date'], name='domain_acco_organiz_06e2af_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['organization', 'entry_type'], name='domain_acco_organiz_10165d_idx'),
        ),
    ]
