# Generated by Django 6.0.3 on 2026-05-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_accounting_foundations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Identificador del proveedor (nubefact | sunat | email | whatsapp | payment_gateway)', max_length=50)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Producción')], default='sandbox', max_length=20)),
                ('base_url', models.URLField(help_text='URL base del servicio — las operaciones pueden usar subpaths o payload/action')),
                ('api_key', models.CharField(help_text='Token / API key principal del servicio', max_length=512)),
                ('api_secret', models.CharField(blank=True, default='', help_text='Secret secundario si el proveedor usa autenticación de dos partes', max_length=512)),
                ('timeout_seconds', models.IntegerField(default=15, help_text='Timeout en segundos para requests a este servicio')),
                ('max_retries', models.IntegerField(default=3, help_text='Máximo de reintentos ante errores temporales')),
                ('rate_limit_per_minute', models.IntegerField(blank=True, help_text='Límite de requests por minuto — null si no aplica o no conocido', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Si False, el sistema no intentará usar este proveedor')),
                ('notes', models.TextField(blank=True, default='', help_text='Notas operacionales (contacto soporte, restricciones, fechas de rotación, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'verbose_name': 'Configuración de Servicio Externo',
                'verbose_name_plural': 'Configuraciones de Servicios Externos',
            },
        ),
        migrations.CreateModel(
            name='ExternalRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Denormalizado de service.provider_name — persiste aunque la config sea eliminada', max_length=50)),
                ('operation', models.CharField(help_text='Operación lógica realizada (create_invoice | query_status | send_email, etc.)', max_length=100)),
                ('request_payload', models.JSONField(blank=True, help_text='Payload enviado al servicio externo (sanitizado — sin tokens ni PII sensible)', null=True)),
                ('response_payload', models.JSONField(blank=True, help_text='Respuesta recibida del servicio externo (completa para auditoría)', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code de la respuesta', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duración del request en milisegundos', null=True)),
                ('success', models.BooleanField(help_text='True si el request fue procesado exitosamente por el proveedor', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si success=False', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Orden asociada al request — null para operaciones no relacionadas con órdenes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_request_logs', to='domain.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
                ('service', models.ForeignKey(blank=True, help_text='Config del servicio usado — SET_NULL para preservar logs si config es eliminada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='domain.externalserviceconfig')),
            ],
            options={
                'verbose_name': 'Log de Request Externo',
                'verbose_name_plural': 'Logs de Requests Externos',
            },
        ),
        migrations.AddIndex(
            model_name='externalserviceconfig',
            index=models.Index(fields=['organization', 'provider_name'], name='domain_exte_organiz_22d79e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalserviceconfig',
            unique_together={('organization', 'provider_name', 'environment')},
        ),
        migrations.AddIndex(
            model_name='externalrequestlog',
            index=models.Index(fields=['organization', 'provider_name', 'created_at'], name='domain_exte_organiz_c0f629_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrequestlog',
            index=models.Index(fields=['organization', 'operation', 'created_at'], name='domain_exte_organiz_92a5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrequestlog',
            index=models.Index(fields=['order', 'provider_name'], name='domain_exte_order_i_6b883a_idx'),
        ),
    ]
