# Generated by Django 6.0.3 on 2026-03-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_cashreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
