# Generated by Django 6.0.3 on 2026-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_organization_logo_image_organization_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='organization',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='dashboard_batch_size',
            field=models.PositiveIntegerField(default=10, help_text='Registros por página en el dashboard'),
        ),
    ]
