# Generated by Django 6.0.3 on 2026-03-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_remove_order_subtotal_remove_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DRAFT', 'Borrador'), ('PAID', 'Pagado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20),
        ),
    ]
