# Generated by Django 6.0.3 on 2026-08-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_order_invoice_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (desarrollo)'), ('izipay', 'Izipay (producción)')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Confirmación'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_rate', models.DecimalField(decimal_places=2, default=0, help_text='% comisión efectivo', max_digits=5)),
                ('card_rate', models.DecimalField(decimal_places=2, default=3.5, help_text='% comisión tarjeta (ej: Niubiz/Izipay)', max_digits=5)),
                ('transfer_rate', models.DecimalField(decimal_places=2, default=0, help_text='% comisión transferencia bancaria', max_digits=5)),
                ('wallet_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='% comisión billetera digital (Yape/Plin)', max_digits=5)),
                ('provider_type', models.CharField(choices=[('mock', 'Mock (desarrollo)'), ('izipay', 'Izipay (producción)')], default='mock', help_text='Proveedor activo de pasarela de pagos', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='domain.organization')),
            ],
            options={
                'verbose_name': 'Configuración de Comisiones de Pago',
                'verbose_name_plural': 'Configuraciones de Comisiones de Pago',
            },
        ),
    ]
