# Generated by Django 6.0.3 on 2026-03-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_order_subtotal_order_tax_amount_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='orders/pdfs/'),
        ),
    ]
