# Generated by Django 6.0.3 on 2026-08-09 23:49

from django.db import migrations


def backfill_existing_payments(apps, schema_editor):
    """
    Antes de esta Fase, todo Payment existente correspondía a una orden PAID
    (el pago se creaba y la orden pasaba a PAID de inmediato). Se backfillea:
      - status='approved' (transacciones ya asimiladas)
      - approved_at=payment_date (snapshot razonable)
      - fee_rate=3.50 para CARD, 0 para el resto (regla hardcodeada previa)
    """
    Payment = apps.get_model('domain', 'Payment')
    for payment in Payment.objects.all():
        payment.status = 'approved'
        payment.approved_at = payment.payment_date
        payment.fee_rate = 3.50 if payment.method == 'CARD' else 0
        payment.save(update_fields=['status', 'approved_at', 'fee_rate'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_alter_payment_options_payment_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_existing_payments, noop),
    ]
