# Generated by Django 6.0.3 on 2026-04-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0018_order_pdf_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(default='Dirección por defecto'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ruc',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
