# Generated by Django 6.0.3 on 2026-04-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0019_organization_address_organization_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], max_length=5)),
                ('document_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='domain.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'document_number')},
            },
        ),
    ]
