# Generated by Django 6.0.3 on 2026-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0021_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('buy_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('origin', models.CharField(default='apimigo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
