# Generated by Django 6.0.3 on 2026-04-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0022_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'sku')},
        ),
    ]
